// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Plugin used to set basic parameters.","parameters":{"cacheLimit":"20","screenWidth":"1000","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"-------------------","status":false,"description":"","parameters":{}},
{"name":"BrCore","status":true,"description":"","parameters":{"Debug":"true"}},
{"name":"BrDrawIcons","status":true,"description":"","parameters":{}},
{"name":"BrFactores","status":true,"description":"","parameters":{"FPM":"100"}},
{"name":"BrMenu","status":true,"description":"","parameters":{}},
{"name":"BrMenuTitulo","status":true,"description":"","parameters":{}},
{"name":"BrMenusStatusPrueba","status":true,"description":"","parameters":{}}
];
